##########################################################################
#
# NAME: 	check_storage_pool.ps1
#
# AUTHOR: 	Martin Weber, atnd GmbH
# EMAIL: 	martin.weber at atnd.de
#
# COMMENT:  Check status of local disk and all windows storage pools
#           for NSClient
#
# CREDITS:  To Nadeschda, my lovely dog ;-)
#
#			Return Values for NRPE:
#			Everything OK - OK (0)
#			Failed - FAILED (2)
#
# CHANGELOG:
# 0.1 2014-08-22 - initial version
#
##########################################################################

$NagiosStatus = "0"
$NagiosDescription = ""

$disks = Get-PhysicalDisk | Sort FriendlyName | select HealthStatus,FriendlyName,OperationalStatus
$pools = Get-StoragePool | Sort FriendlyName | select FriendlyName,HealthStatus,OperationalStatus

foreach ($pool in $pools)
    {
        if ($pool.HealthStatus -eq "Healthy") { $health = "OK" } else {
         $health = "FAILED"
         $NagiosStatus = "2"
         }
        
        if ($pool.OperationalStatus -eq "OK") { $oper = "OK" } else {
         $oper = "FAILED"
         $NagiosStatus = "2"
         }
        
        $NagiosDescription = $NagiosDescription + "(POOL:"+$pool.FriendlyName+" Health:"+$health+" Operational:"+$oper+") "
    }

foreach ($disk in $disks)
    {
        if ($disk.HealthStatus -eq "Healthy") { $health = "OK" } else {
         $health = "FAILED"
         $NagiosStatus = "2"
         }
        
        if ($disk.OperationalStatus -eq "OK") { $oper = "OK" } else {
         $oper = "FAILED"
         $NagiosStatus = "2"
         }
        
        $NagiosDescription = $NagiosDescription + "(DISK:"+$disk.FriendlyName+" Health:"+$health+" Operational:"+$oper+") "
    }

if ($NagiosStatus -eq "2") 
{
	Write-Host "FAILED:"$NagiosDescription


} 
else 
{	
Write-Host "OK:"$NagiosDescription

}



exit $NagiosStatus
# SIG # Begin signature block
# MIIY+AYJKoZIhvcNAQcCoIIY6TCCGOUCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQU5JhLPQSKEoPoc7RdFW/p4/0K
# wS+gggzPMIIGVzCCBT+gAwIBAgICD5kwDQYJKoZIhvcNAQEFBQAwgYwxCzAJBgNV
# BAYTAklMMRYwFAYDVQQKEw1TdGFydENvbSBMdGQuMSswKQYDVQQLEyJTZWN1cmUg
# RGlnaXRhbCBDZXJ0aWZpY2F0ZSBTaWduaW5nMTgwNgYDVQQDEy9TdGFydENvbSBD
# bGFzcyAzIFByaW1hcnkgSW50ZXJtZWRpYXRlIE9iamVjdCBDQTAeFw0xNDA4MDYw
# NzQyMjNaFw0xNzA4MDYxMDEwMDNaMIGPMRkwFwYDVQQNExBtWHJYdE5ldzdVR0Vn
# YzIwMQswCQYDVQQGEwJERTEPMA0GA1UECBMGQmVybGluMQ8wDQYDVQQHEwZCZXJs
# aW4xEjAQBgNVBAoTCUFUTkQgR21iSDESMBAGA1UEAxMJQVRORCBHbWJIMRswGQYJ
# KoZIhvcNAQkBFgxhdG5kQGF0bmQuZGUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
# ggEKAoIBAQDxidve5GK3cfrXdYm0vN5J/QcGjQGTUY2FE1f3GFdQj2WL29unUBZW
# tJLolXDrMCzdXYqhgBBG3ogk7l7P8gWOSuG9qqOhTJYXby0VXIVv3o3c96hNwtuU
# HOGUgTeDpU/hRITDJCUvPw03yw4GiYkQ3FUtZO4zXUYS8Rpatxj+9zjY4RJSUyNQ
# KWzXJ2t06oih4UROC3ksWBqOMcfTrE1xHCXfvSubZrHo4WVBMcjxTkVIbtes4Cxz
# ZpVW1xgsOGifWg3WIhZtv7VtxmQBr13FhpSb+GHvfSaEHYZsqt6BUQzxrQjv0rGw
# LCJshli58BW2CKOQcz8Ph/qz8yz2y+SdAgMBAAGjggK8MIICuDAJBgNVHRMEAjAA
# MA4GA1UdDwEB/wQEAwIHgDAiBgNVHSUBAf8EGDAWBggrBgEFBQcDAwYKKwYBBAGC
# Nz0BATAdBgNVHQ4EFgQU3FEt5E+LVmUQw2jvjB1MmXsi/AcwHwYDVR0jBBgwFoAU
# l8pzU6Uus4kapkJ9qQ+T+4eMARgwggFMBgNVHSAEggFDMIIBPzCCATsGCysGAQQB
# gbU3AQIDMIIBKjAuBggrBgEFBQcCARYiaHR0cDovL3d3dy5zdGFydHNzbC5jb20v
# cG9saWN5LnBkZjCB9wYIKwYBBQUHAgIwgeowJxYgU3RhcnRDb20gQ2VydGlmaWNh
# dGlvbiBBdXRob3JpdHkwAwIBARqBvlRoaXMgY2VydGlmaWNhdGUgd2FzIGlzc3Vl
# ZCBhY2NvcmRpbmcgdG8gdGhlIENsYXNzIDMgVmFsaWRhdGlvbiByZXF1aXJlbWVu
# dHMgb2YgdGhlIFN0YXJ0Q29tIENBIHBvbGljeSwgcmVsaWFuY2Ugb25seSBmb3Ig
# dGhlIGludGVuZGVkIHB1cnBvc2UgaW4gY29tcGxpYW5jZSBvZiB0aGUgcmVseWlu
# ZyBwYXJ0eSBvYmxpZ2F0aW9ucy4wNgYDVR0fBC8wLTAroCmgJ4YlaHR0cDovL2Ny
# bC5zdGFydHNzbC5jb20vY3J0YzMtY3JsLmNybDCBiQYIKwYBBQUHAQEEfTB7MDcG
# CCsGAQUFBzABhitodHRwOi8vb2NzcC5zdGFydHNzbC5jb20vc3ViL2NsYXNzMy9j
# b2RlL2NhMEAGCCsGAQUFBzAChjRodHRwOi8vYWlhLnN0YXJ0c3NsLmNvbS9jZXJ0
# cy9zdWIuY2xhc3MzLmNvZGUuY2EuY3J0MCMGA1UdEgQcMBqGGGh0dHA6Ly93d3cu
# c3RhcnRzc2wuY29tLzANBgkqhkiG9w0BAQUFAAOCAQEADDY9bv/eskRFYn6cx9D/
# /0Awva/eiVg6qOIXaj1wHmh0GIlwj7/9EUAHeEAkEf5pc736SsT2PIJrlg25KOL9
# QAq+3AXabyfdDi6POr9j2vC9uIk21fVBPaVThmXR2g+7ZJ2wnW8EWt6epBvgP8wZ
# nUyB99nJmzwKySt0nv83+ujcViaKanbTvphlVVpmILKPekSW3Ho0Ag6l93zaXX3k
# Ls9tSiC1s6tod1FmBV++kzbKUoiNJzorG41OMEM4CHTadkOjvyNYBrwfNPx/cZ0R
# xJxEsvJjNmpRsVz+aswGl3Zu8kxJUljTMeZc9N+/fEcN98xnblDbzpFbRFkKiQOn
# HjCCBnAwggRYoAMCAQICASYwDQYJKoZIhvcNAQEFBQAwfTELMAkGA1UEBhMCSUwx
# FjAUBgNVBAoTDVN0YXJ0Q29tIEx0ZC4xKzApBgNVBAsTIlNlY3VyZSBEaWdpdGFs
# IENlcnRpZmljYXRlIFNpZ25pbmcxKTAnBgNVBAMTIFN0YXJ0Q29tIENlcnRpZmlj
# YXRpb24gQXV0aG9yaXR5MB4XDTA3MTAyNDIyMDM1NVoXDTE3MTAyNDIyMDM1NVow
# gYwxCzAJBgNVBAYTAklMMRYwFAYDVQQKEw1TdGFydENvbSBMdGQuMSswKQYDVQQL
# EyJTZWN1cmUgRGlnaXRhbCBDZXJ0aWZpY2F0ZSBTaWduaW5nMTgwNgYDVQQDEy9T
# dGFydENvbSBDbGFzcyAzIFByaW1hcnkgSW50ZXJtZWRpYXRlIE9iamVjdCBDQTCC
# ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANg61U+dXPPCDSIKlQisOROf
# Uxhi+aYraY6fGTeit7zAb5qOowlyO3sKmBNbGVDX4px4wMIX4ux66QT5Yv8RttVb
# cWxGGeACOMLcunJ20RAYmIpo4phuSMpKptwrHAMG2+h8TRI/YmCLknD28ROixGUc
# v2ll1cAQ0JwJ1P5MkiqtPqzQ1pGkOOxrmGvngI7qar3TwybQgO5qN7dvNDe5QdoG
# 6NHRN+xyIac2sqXh28sJ6komJDkpBDqK7f5KdFs2t81NcmuVnZAd0w2tDCzj/Gfn
# sQGsTDL7Wzoyg9BnVQul/MmYMAN3/KM8qsAN4PNQWb95YYR9cA2UNUOqbK06Vr8C
# AwEAAaOCAekwggHlMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgEGMB0G
# A1UdDgQWBBSXynNTpS6ziRqmQn2pD5P7h4wBGDAfBgNVHSMEGDAWgBROC+8apEBb
# pRdphzDKNGhD0EGu8jA9BggrBgEFBQcBAQQxMC8wLQYIKwYBBQUHMAKGIWh0dHA6
# Ly93d3cuc3RhcnRzc2wuY29tL3Nmc2NhLmNydDBbBgNVHR8EVDBSMCegJaAjhiFo
# dHRwOi8vd3d3LnN0YXJ0c3NsLmNvbS9zZnNjYS5jcmwwJ6AloCOGIWh0dHA6Ly9j
# cmwuc3RhcnRzc2wuY29tL3Nmc2NhLmNybDCBgAYDVR0gBHkwdzB1BgsrBgEEAYG1
# NwECATBmMC4GCCsGAQUFBwIBFiJodHRwOi8vd3d3LnN0YXJ0c3NsLmNvbS9wb2xp
# Y3kucGRmMDQGCCsGAQUFBwIBFihodHRwOi8vd3d3LnN0YXJ0c3NsLmNvbS9pbnRl
# cm1lZGlhdGUucGRmMBEGCWCGSAGG+EIBAQQEAwIAATBQBglghkgBhvhCAQ0EQxZB
# U3RhcnRDb20gQ2xhc3MgMyBQcmltYXJ5IEludGVybWVkaWF0ZSBPYmplY3QgU2ln
# bmluZyBDZXJ0aWZpY2F0ZXMwDQYJKoZIhvcNAQEFBQADggIBALjrpTgsq5A4z76Q
# aRmVL5ZOSBA1RbBDcS65DmcPYYRY7WUa4NhRXJbE32nK+2K/NepKaSPy9n9g22Up
# Jei6XvlIWSB0XJmY+n7XTq9DljuIiA6B8dCmqa8d9ec+BFvokntiSlMdO3qvlKIF
# AtoPraGnMhZqHV2I8d3F2n6RsApTEk3b783qn0jfv7J8AZL5gWN5oG8Ol9mQRKVQ
# uIdLXNiconqtS5HzEXTmqCNC1CZcqD2FoDXsUwjdti0cIchISsTIOrBuL0Pm32QJ
# dYb+DmjSY1SgZuSe79tcdKCo3EDpe2fWOz7ShtMWIdHhMlKj5sLhY350Qxq+7Cmu
# VuEYEfplCzc0DrRHmfhvtJlO0jWwR2S1/umvtpojwoLIOLbUpC40Ic4D70w4QVAv
# Da1AyCgn6et8K9FwTiyIGMh8PyRQXctTVGef16EJmAsLiyFpunKmEnuwWg5pfMcG
# uix6lQ8HlGMjVlelOCpjxCBqnoRDj9rY0D/QfZWSEykWwNhoyuX+dZi29BDhfDCe
# uZApIDXjHFazCv2GcXz7vAsujJTjVGnEeE0eCvgPM7niVteJhByc32/FC4+Zg1EG
# a0QdbzC8vvk6GQvM+ua8Ij89VHW4CmR/f2W7opBJw/In97u5frdoh4LNQ+xsrKsp
# x9BA4rs6AhgxUHeuM7GpqMYtRXD/MYILkzCCC48CAQEwgZMwgYwxCzAJBgNVBAYT
# AklMMRYwFAYDVQQKEw1TdGFydENvbSBMdGQuMSswKQYDVQQLEyJTZWN1cmUgRGln
# aXRhbCBDZXJ0aWZpY2F0ZSBTaWduaW5nMTgwNgYDVQQDEy9TdGFydENvbSBDbGFz
# cyAzIFByaW1hcnkgSW50ZXJtZWRpYXRlIE9iamVjdCBDQQICD5kwCQYFKw4DAhoF
# AKCBpDAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4w
# DAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQU9qpm40BM1VY8zeuErF7daj4n
# Bq4wRAYKKwYBBAGCNwIBDDE2MDSgFoAUAEQAaQBzAGsAIABDAGgAZQBjAGuhGoAY
# aHR0cHM6Ly9zdXBwb3J0LmF0bmQuZGUgMA0GCSqGSIb3DQEBAQUABIIBALA3okbT
# ljOZIxIuHyYeTkxwWWDw9Ast52Qoq0AJY7iBtRMKpCXZSAvc8pG7fzHYVWZpcI6y
# fSlvZ1bgoO7uAppeqGb/oBBto3Tr10nu5eB64hzAO/c3QMlULIn6lYMIHB5USt7z
# CkVNWLWmRxvG05X2Z5G6uoYFkgQq+1G87BGg3DBrSQNhANm5TuWVXOXwUFQyOXS9
# mX1KTw5AwciP4cP02mWLjP4XHMqaN2MUs+hjWM10Lkh0/llA6oS4U6Hujej25qN/
# DT5QQPFlY9ppteNGllE6JYX2z4EXYTrQJKxGXIbzs0hVht93IARwgW9gLXiEuESG
# b27a65ISJtbbUrihggktMIIJKQYKKwYBBAGCNwMDATGCCRkwggkVBgkqhkiG9w0B
# BwKgggkGMIIJAgIBAzELMAkGBSsOAwIaBQAwgcgGCyqGSIb3DQEJEAEEoIG4BIG1
# MIGyAgEBBgsrBgEEAYG1NwECADAhMAkGBSsOAwIaBQAEFDJxAIWmzthhfX9m1J+g
# 3umM3/J3AgM7+tEYDzIwMTQwODIyMTIwODM0WjADAgEBoGKkYDBeMSkwJwYDVQQD
# EyBTdGFydENvbSBUaW1lLVN0YW1waW5nIEF1dGhvcml0eTExMC8GA1UEChMoU3Rh
# cnRDb20gTHRkLiAoU3RhcnQgQ29tbWVyY2lhbCBMaW1pdGVkKaCCBeYwggXiMIID
# yqADAgECAgFAMA0GCSqGSIb3DQEBBQUAMH0xCzAJBgNVBAYTAklMMRYwFAYDVQQK
# Ew1TdGFydENvbSBMdGQuMSswKQYDVQQLEyJTZWN1cmUgRGlnaXRhbCBDZXJ0aWZp
# Y2F0ZSBTaWduaW5nMSkwJwYDVQQDEyBTdGFydENvbSBDZXJ0aWZpY2F0aW9uIEF1
# dGhvcml0eTAeFw0xMTAxMzEwMDAwMDJaFw0yMTAxMzEyMzU5NTlaMF4xKTAnBgNV
# BAMTIFN0YXJ0Q29tIFRpbWUtU3RhbXBpbmcgQXV0aG9yaXR5MTEwLwYDVQQKEyhT
# dGFydENvbSBMdGQuIChTdGFydCBDb21tZXJjaWFsIExpbWl0ZWQpMIIBIjANBgkq
# hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuNqiP2F9I40yh01RLyrgRnc6enNAD15y
# 1II89YCxBZDsZ+twiWWEJ/3Qk5oSrg80L0gUMmCVCl1OThGfslOajnFdagQAnyTu
# t/3ST+VVdAqy86h3Lpcb+UZIdWY4QtGGHMlANtFIAHAx1ZKZbMlh5a9+DLZVtN/2
# apMpy0tDzr0PseD2Y9OkmTIE9drqpFm099s4tZP/nlmavntgdcbtTd+jTKSIvmPz
# PHFljarSJFgO04usK0qP8N7oDZeCmS2LeYJ3gOhazUdolQxx7HD3bbG2zdXXHDj8
# loDnAVvEEoMDulBmkOOOEVp21/pTkGn4M+QUkaP3EI6IgFAWEU+S9QIDAQABo4IB
# ijCCAYYwDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCB4AwFgYDVR0lAQH/BAww
# CgYIKwYBBQUHAwgwHQYDVR0OBBYEFHckhtE28aq5hJSgQKuQTENGcXCLMB8GA1Ud
# IwQYMBaAFE4L7xqkQFulF2mHMMo0aEPQQa7yMCMGA1UdEgQcMBqGGGh0dHA6Ly93
# d3cuc3RhcnRzc2wuY29tLzBpBggrBgEFBQcBAQRdMFswJwYIKwYBBQUHMAGGG2h0
# dHA6Ly9vY3NwLnN0YXJ0c3NsLmNvbS9jYTAwBggrBgEFBQcwAoYkaHR0cDovL2Fp
# YS5zdGFydHNzbC5jb20vY2VydHMvY2EuY3J0MDIGA1UdHwQrMCkwJ6AloCOGIWh0
# dHA6Ly9jcmwuc3RhcnRzc2wuY29tL3Nmc2NhLmNybDBKBgNVHSAEQzBBMD8GCysG
# AQQBgbU3AQIAMDAwLgYIKwYBBQUHAgEWImh0dHA6Ly93d3cuc3RhcnRzc2wuY29t
# L3BvbGljeS5wZGYwDQYJKoZIhvcNAQEFBQADggIBAJqtE0h5RYQmdMnZIuDQ6B/N
# K95j4IJqPXkmUINQGl9vf2OhW+1svNykvUbdb2Eej3AYoob0v9rZEC+siDfllIZq
# TcK4U7owjP6fDfgeJAUWnJMCE2pailhB6+fKrTQR8bfqBq5X5rU57zb523bA/DK3
# j3GtPMc28OFn/RrK2oxL+WbajB9azmYG6J3zFI6+r/dTWE9H1gK0t2r70jE5Nuxz
# aVZacDgs+72Tzspoz7eqMhOTkSYtw5Ztb/oHjVhMdEWsL4SJ+QZu0NWNBNGygWIJ
# CRn6SHQMfz+MH0N2SZmoaRTIytzgfoObkneQyfADJ/WfPcdmAktbhyd1cK3si3Kl
# 6XvDU8bWVHcy/2ZNP1ZssgMLTSO5WhVKRnTNM7GzSOVNVbYHf47B45JklFKk8lx+
# sDhIVX6sRsiu49p2iGZoHXJVSTyaxoC766Vl9iSAV5Yulv9xqbFfGEcQQU1jpm7k
# aSd46anHkGetjsWGD+7No8ww268Ve7wnM5IheBf6lv6qMzS0k/l1jbibmpw5mCvA
# fVu4o53bLT5kBpmf54li3JJc2+fgbgaqxuaDVL0R0tr7YLyrEOI3oqdbuKiC1NXe
# Cm4k3BO1puqKCrTy7TTQxNZaMjSyJfhW3nBV6QSdWYvaOVAZ9xTNqYmH2F7Qp0Md
# WgpYtQJvIcLedAoH8LBCMYICOTCCAjUCAQEwgYIwfTELMAkGA1UEBhMCSUwxFjAU
# BgNVBAoTDVN0YXJ0Q29tIEx0ZC4xKzApBgNVBAsTIlNlY3VyZSBEaWdpdGFsIENl
# cnRpZmljYXRlIFNpZ25pbmcxKTAnBgNVBAMTIFN0YXJ0Q29tIENlcnRpZmljYXRp
# b24gQXV0aG9yaXR5AgFAMAkGBSsOAwIaBQCggYwwGgYJKoZIhvcNAQkDMQ0GCyqG
# SIb3DQEJEAEEMBwGCSqGSIb3DQEJBTEPFw0xNDA4MjIxMjA4MzRaMCMGCSqGSIb3
# DQEJBDEWBBS1IKFLHJTH3L7eBO0m2AhGkd5qDzArBgsqhkiG9w0BCRACDDEcMBow
# GDAWBBSWL93XbGFFra+l6a2Y4wINCCHdgTANBgkqhkiG9w0BAQEFAASCAQBOzctm
# C8BcuXWtcH8SubNaFQ0MfIvvv0yOlNo7e15PObf4wZ4cQKeRn+S12HWVwG1IXjWI
# Yx2NXvttKOhAJEDIxe4j8D8G6R81fWVMU9spTX7eHjgi+9K3X0oloPZCxczGrwwn
# 2sPE+zAoo6G5xE0eSA43vl+5hCj6oEAl2TztYUj0UkGziGNmhFW8pnNs8KCUk7gD
# Vt6DaHwNlhJK2Ik57Zl/r8ZoNjbE3tXjfARet3gfE+CZwr2ZD7bw7elG8nmdPHA4
# OiVNSHvC6AeH5SZfZJDJOlialRxkaDmLJFyXnxzmNHbMgNKLL4dRkM8KMtmCkfJj
# wMwigft3TBPwjMVh
# SIG # End signature block
